version: '3.7'

services:
  pgadmin:
    image: zen/pgadmin4:latest
    hostname: pgadmin
    container_name: pgadmin
    build:
      context: ./
      dockerfile: ./deploy/postgres/Dockerfile
      args:
        PGADMIN_EMAIL: ${PGADMIN_EMAIL}
    environment:
      PGADMIN_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres-network
    restart: always
  
  apollo-router:
    image: ghcr.io/apollographql/router:v1.4.0
    container_name: apollo-router
    environment:
      APOLLO_GRAPH_REF: ${APOLLO_GRAPH_REF}
      APOLLO_KEY: ${APOLLO_KEY}
      AUTH_API_PORT: ${AUTH_API_PORT}
    networks:
      - postgres-network
    ports:
      - 4000:4000
    volumes:
      - ./router-prod.yaml:/dist/config/router.yaml

  postgres-auth-api:
    image: postgres:14
    container_name: postgres-auth-api
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${AUTH_PGDATABASE}
    volumes:
      - postgres-auth-api:/var/lib/postgresql/data
    ports:
      - ${AUTH_PGDATABASE_PORT}:5432
    networks:
      - postgres-network
  subgraph-auth-api:
    image: zen/subgraph-auth-api
    container_name: subgraph-auth-api
    build:
      context: ./
      dockerfile: ./deploy/api/Dockerfile
      args:
        API_NAME: Auth
        API_PORT: ${AUTH_API_PORT}
        PROJECT_NAME: auth-api
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      AUTH_API_PORT: ${AUTH_API_PORT}
      AUTH_PGDATABASE: ${AUTH_PGDATABASE}
    ports:
      - '${AUTH_API_PORT}:${AUTH_API_PORT}'
    networks:
      - postgres-network
    depends_on:
      - postgres-auth-api

volumes:
  postgres-auth-api:
  pgadmin:
networks:
  postgres-network:
    driver: bridge
    name: postgres-network