version: '2'
name: zen

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    build:
      context: ./
      dockerfile: ./deploy/postgres/Dockerfile
      args:
        PGADMIN_EMAIL: ${PGADMIN_EMAIL}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres
    restart: unless-stopped

  postgres-auth-api:
    image: postgres:14
    container_name: postgres-auth-api
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${AUTH_PGDATABASE}
    volumes:
      - postgres-auth-api:/var/lib/postgresql/data
    ports:
      - ${AUTH_PGDATABASE_PORT}:5432
    networks:
      - postgres


volumes:
  postgres-auth-api:
  pgadmin:
networks:
  postgres:
    driver: bridge
